### PR TITLE
Remove temporary pr-4995.patch

### LINKED ISSUE #98: Nightly feedstock build failed
Nightly feedstock build failure for tiledbfeedstock_CI at https://dev.azure.com/TileDB-Inc/CI/_build?definitionId=4&_a=summary

### PR DESCRIPTION
**Pull request by jdblischak**
Closes #98

Details in https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/98#issuecomment-2137687678

### CODE REVIEW

**Review by teo-tsirpanis — APPROVED** [review]
That Core PR might be responsible for failures in MariaDB, but let's merge this for the feedstock nightlies.

**Comment by jdblischak** [comment]
Also, to demonstrate that this will fix the nightly builds, I manually deleted the patch in the nightly-build branch and pushed to my fork. The [builds](https://dev.azure.com/jdblischak/feedstock-builds/_build/results?buildId=817&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) haven't completed yet, but they no longer fail at the early stage of applying the patches.

**Comment by jdblischak** [comment]
> The [builds](https://dev.azure.com/jdblischak/feedstock-builds/_build/results?buildId=817&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) haven't completed yet

Update: The linux-64 build completed successfully. However, the build is going to fail since it is unable to upload the binary to anaconda.org, since I didn't update my fork to handle this.

**Review by ihnorton — APPROVED** [review]
Thanks. It would be nice if we could use `patch -N` here, but I guess the call to `patch` is buried somewhere inside of conda-build.

**Comment by jdblischak** [comment]
> Thanks. It would be nice if we could use `patch -N` here, but I guess the call to `patch` is buried somewhere inside of conda-build.

"buried" is definitely the correct term. I did a quick search of how they call `patch` from within `conda-build`, and they do all sorts of acrobats, mostly to avoid potential problems with different line endings. The Issue https://github.com/conda/conda-build/issues/4054 describes some of the difficulties. And I think `patch` is actually executed by the function [`apply_one_patch()`](https://github.com/conda/conda-build/blob/d9edc578d067013b247437aa4d907e64fd4512e6/conda_build/source.py#L899) in `source.py`

**Pull request merged**
